### ISSUE TITLE
怎么设置数据库？

### ISSUE THREAD

**Issue by Geek-007** [jinhesui/msg#1]
![image](https://user-images.githubusercontent.com/25733662/52172913-832ef500-27b4-11e9-9f6f-32dfb8b93e55.png)

**Comment by jinhesui** [comment]
修改 inc/conn.php 这一行 $conn = new mysqli("localhost", "homestead", "secret", "msg"); 为你自己的数据库配置，数据库很简单的，你可以根据 index.php 里的字段新建一个自己的数据表，当然也可以使用以下建表语句：
CREATE TABLE IF NOT EXISTS `posts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` char(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `username` char(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `content` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
